### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test tap-linkedin-ads

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  workflow_dispatch:
    inputs: {}

jobs:
  pytest:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        pipx install poetry
        poetry --version
    - name: Install dependencies
      run: |
        poetry install
    - name: Test with pytest
      id: test_pytest
      continue-on-error: false
      env:
         TAP_LINKEDIN_ADS_ACCESS_TOKEN: ${{ secrets.access_token }}
         TAP_LINKEDIN_ADS_ACCOUNTS: ${{ secrets.accounts }}
         TAP_LINKEDIN_ADS_OWNER: ${{ secrets.owner }}
         TAP_LINKEDIN_ADS_CAMPAIGN: ${{ secrets.campaign }}
         TAP_LINKEDIN_ADS_CAMPAIGN_GROUP: ${{ secrets.campaign_group }}
         TAP_LINKEDIN_ADS_CREATIVE: ${{ secrets.creative }}
      run: |
        poetry run pytest --capture=no
